name: Tests

on:
  push:
    branches:
      - main
    paths:
      - VolScript.ps1
      - src/**
      - config/config.json
      - .github/workflows/tests.yml
  pull_request:
    branches:
      - main
    paths:
      - VolScript.ps1
      - src/**
      - config/config.json
      - .github/workflows/tests.yml

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pester
        shell: powershell
        run: |
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          Install-PackageProvider NuGet -MinimumVersion 2.8.5.201 -Force
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Pester -Force -SkipPublisherCheck -Scope CurrentUser

      - name: Run tests
        shell: powershell
        run: ./src/Test/Run-Tests.ps1
